PROGRAM DOPPLER
    CHARACTER :: OTOWARDSCHAR
    CHARACTER :: STOWARDSCHAR
    CHARACTER(LEN=15) :: FSTRING
    CHARACTER(LEN=15) :: VOSTRING
    CHARACTER(LEN=15) :: VSSTRING
    INTEGER :: FSTRINGINDEXM
    INTEGER :: FSTRINGINDEXK
    LOGICAL :: FSTRINGISM = .FALSE.
    LOGICAL :: FSTRINGISK = .FALSE.
    INTEGER :: VOSTRINGINDEXS
    INTEGER :: VOSTRINGINDEXK
    INTEGER :: VOSTRINGINDEXM
    INTEGER :: VSSTRINGINDEXS
    INTEGER :: VSSTRINGINDEXK
    INTEGER :: VSSTRINGINDEXM
    LOGICAL :: VOSTRINGISS = .FALSE.
    LOGICAL :: VOSTRINGISK = .FALSE.
    LOGICAL :: VOSTRINGISM = .FALSE.
    LOGICAL :: VSSTRINGISS = .FALSE.
    LOGICAL :: VSSTRINGISK = .FALSE.
    LOGICAL :: VSSTRINGISM = .FALSE.
    LOGICAL :: OTOWARDS = .FALSE.
    LOGICAL :: OAWAY = .FALSE.
    LOGICAL :: STOWARDS = .FALSE.
    LOGICAL :: SAWAY = .FALSE.
    DOUBLE PRECISION :: FO
    DOUBLE PRECISION :: F
    INTEGER :: V = 299792458
    DOUBLE PRECISION :: VO
    DOUBLE PRECISION :: VS
    WRITE(*,'(A)',ADVANCE='NO') "IS THE OBSERVER HEADING TOWARD THE SOURCE (T), OR AWAY FROM THE SOURCE(A): "
    READ*,OTOWARDSCHAR
    IF(OTOWARDSCHAR == 'T') THEN
        OTOWARDS = .TRUE.
    ELSE IF(OTOWARDSCHAR == 'A') THEN
        OAWAY = .TRUE.
    ELSE
        PRINT*,"YOU MUST ANSWER THIS QUESTION."
        CALL EXIT(1)
    END IF
    WRITE(*,'(A)',ADVANCE='NO') "IS THE SOURCE HEADING TOWARD THE OBSERVER (T), OR AWAY FROM THE OBSERVER(A): "
    READ*,STOWARDSCHAR
    IF(STOWARDSCHAR == 'T') THEN
        STOWARDS = .TRUE.
    ELSE IF(STOWARDSCHAR == 'A') THEN
        SAWAY = .TRUE.
    ELSE
        PRINT*,"YOU MUST ANSWER THIS QUESTION."
        CALL EXIT(1)
    END IF
    WRITE(*,'(A)',ADVANCE='NO') "ENTER FREQUENCY (M FOR MHZ, K FOR KHZ): "
    READ*,FSTRING
    FSTRINGINDEXM = INDEX(FSTRING,"M")
    FSTRINGINDEXK = INDEX(FSTRING,"K")
    IF(FSTRINGINDEXM > 0) THEN
        FSTRINGISM = .TRUE.
    ELSE IF(FSTRINGINDEXK > 0) THEN
        FSTRINGISK = .TRUE.
    ELSE
        PRINT*,"ENTER M OR K"
        CALL EXIT(1)
    END IF
    IF(FSTRINGISM .EQV. .TRUE.) THEN
        READ(FSTRING(:FSTRINGINDEXM-1),*)F
        F=F*1e6
    ELSE IF (FSTRINGISK .EQV. .TRUE.) THEN
        READ(FSTRING(:FSTRINGINDEXK-1),*)F
        F=F*1e3
    END IF
    WRITE(*,'(A)',ADVANCE='NO') "ENTER OBSERVER VELOCITY (S FOR M/S, K FOR KNOTS, M FOR MACH): "
    READ*,VOSTRING
    VOSTRINGINDEXS = INDEX(VOSTRING,"S")
    VOSTRINGINDEXK = INDEX(VOSTRING, "K")
    VOSTRINGINDEXM = INDEX(VOSTRING, "M")
    IF(VOSTRINGINDEXS > 0) THEN
        VOSTRINGISS = .TRUE.
    ELSE IF(VOSTRINGINDEXK > 0) THEN
        VOSTRINGISK = .TRUE.
    ELSE IF(VOSTRINGINDEXM > 0) THEN
        VOSTRINGISM = .TRUE.
    ELSE
        PRINT*,"ENTER S OR K OR M"
        CALL EXIT(1)
    END IF
    IF(VOSTRINGISS .EQV. .TRUE.) THEN
        READ(VOSTRING(:VOSTRINGINDEXS-1),*)VO
    ELSE IF(VOSTRINGISK .EQV. .TRUE.) THEN
        READ(VOSTRING(:VOSTRINGINDEXK-1),*)VO
        VO=VO*1.944
    ELSE IF(VOSTRINGISM .EQV. .TRUE.) THEN
        READ(VOSTRING(:VOSTRINGINDEXM-1),*)VO
        VO=VO*343
    END IF
   

    WRITE(*,'(A)',ADVANCE='NO') "ENTER SOURCE VELOCITY (S FOR M/S, K FOR KNOTS, M FOR MACH): "
    READ*,VSSTRING
    VSSTRINGINDEXS = INDEX(VSSTRING,"S")
    VSSTRINGINDEXK = INDEX(VSSTRING, "K")
    VSSTRINGINDEXM = INDEX(VSSTRING, "M")
    IF(VSSTRINGINDEXS /= 0) THEN
        VSSTRINGISS = .TRUE.
    ELSE IF(VSSTRINGINDEXK /= 0) THEN
        VSSTRINGISK = .TRUE.
    ELSE IF(VSSTRINGINDEXM /= 0) THEN
        VSSTRINGISM = .TRUE.
    ELSE
        PRINT*,"ENTER S OR K OR M"
        CALL EXIT(1)
    END IF
    IF(VSSTRINGISS .EQV. .TRUE.) THEN
        READ(VSSTRING(:VSSTRINGINDEXS-1),*)VS
    ELSE IF(VSSTRINGISK .EQV. .TRUE.) THEN
        READ(VSSTRING(:VSSTRINGINDEXK-1),*)VS
        VS=VS*1.944
    ELSE IF(VSSTRINGISM .EQV. .TRUE.) THEN
        READ(VSSTRING(:VSSTRINGINDEXM-1),*)VS
        VS=VS*343
    END IF
    IF(OTOWARDS .EQV. .TRUE.) THEN
        IF(STOWARDS .EQV. .TRUE.) THEN
            FO=F*(V+VO)/(V-VS)
            WRITE(*,'(A)',ADVANCE='NO') "OBSERVED FREQUENCY (HZ): "
            PRINT*,FO
            CALL EXIT(0)
        ELSE IF(SAWAY .EQV. .TRUE.) THEN
            FO=F*(V+VO)/(V+VS)
            WRITE(*,'(A)',ADVANCE='NO') "OBSERVED FREQUENCY (HZ): "
            PRINT*,FO
            CALL EXIT(0)
        END IF
    ELSE IF(OAWAY .EQV. .TRUE.) THEN
        IF(STOWARDS .EQV. .TRUE.) THEN
            FO=F*(V-VO)/(V-VS)
            WRITE(*,'(A)',ADVANCE='NO') "OBSERVED FREQUENCY (HZ): "
            PRINT*,FO
            CALL EXIT(0)
        ELSE IF(SAWAY .EQV. .TRUE.) THEN
            FO=F*(V-VO)/(V+VS)
            WRITE(*,'(A)',ADVANCE='NO') "OBSERVED FREQUENCY (HZ): "
            PRINT*,FO
            CALL EXIT(0)
        END IF
    END IF
END PROGRAM DOPPLER